fix: repeat versions in dev-dependencies
Cargo is no longer happy with me not specifying versions of dev-dependencies. Previously this was okay if I only wanted to update the feature set of a dependency for tests.

On stable
```
warning: dependency (fake) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: dependency (serde) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: dependency (zeroize) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
```

On nightly
```
error: failed to parse manifest at `/home/runner/work/redact/redact/Cargo.toml`

Caused by:
  dependency (fake) specified without providing a local path, Git repository, version, or workspace dependency to use
```